name: Bug report
description: |
  Create a bug report to help us improve and fix undocumented or unknown
  issues.
title: 'BUG: '
assignees:
  - funilrys
labels: bug
projects: ['spirillen/ITT', 'funilrys/pyfunceble']
body:
  - type: textarea
    id: bug_description
    attributes:
      label: What happened?
      description: |
        Please be as clear as possible in your description of what the bug is.
      placeholder: Thanks for taking the time to fill out this bug report!
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration?
      description: |
        A clear representation of what you changed into the `.PyFunceble.yaml` and/or what you put into your `.PyFunceble.overwrite.yaml` file.
      placeholder: Tell us what you see!
    validations:
      required: false

  - type: textarea
    id: Reproduction
    attributes:
      label: Reproduction
      description: |
        A clear description of the steps to follow to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
        4.
    validations:
      required: false

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
      placeholder:
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: |
        If applicable, add screenshots to help explain your problem.
      placeholder: |
        "![Screenshot of example.com](img-src)"
        **INFO**: You can copy paste images directly into this field.
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: false

  - type: dropdown
    id: OS
    attributes:
      label: Operating System
      description: What is your Operating System where you found this bug
      multiple: true
      options:
        - Arch Linux (6.9.3)
        - Arch Linux (6.8.8)
        - Arch Linux (6.8.2)
        - Arch Linux (6.7.6)
        - Debian 12
        - Debian 11
        - Debian 10
        - Ubuntu 24.04 LTS
        - Ubuntu 23.10
        - Ubuntu 22.04 LTS
        - Ubuntu 20.04 LTS
        - Linux Other
        - Unix. *BSD like OS
        - Spyware OS socks like Windows or MacOS
        # That typo isn't a accident *smirk*

  # You need to use "" when the option starts or ends with a Zero
  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      description: What python version did you use
      multiple: true
      options:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
        - '4.x'

  - type: dropdown
    id: pyFunceble_version
    attributes:
      label: PyFunceble Version
      description: Which PyFunceble Version did you use
      multiple: true
      options:
        - 4.2.24-dev
        - 4.2.23-dev
        - 4.2.22-dev
        - 4.2.21-dev
        - 4.2.20-dev
        - 4.2.19-dev
        - 4.2.0
        - 4.1.0
        - 4.1.2
        - 4.1.3

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Additional information you might like to add.
      placeholder: Add any other context about the problem here.
