name: Feature request (@PyFunceble)
description: |
  Suggest a feature or an idea for this project.
title: 'FEATURE: '
assignees:
  - funilrys
labels:
  - features
  - enhancement
projects: ['spirillen/ITT', 'funilrys/pyfunceble']
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: |
        A clear description of the feature you wish PyFunceble had.
      placeholder: |
        Example: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: |
        A clear description of the solution that you'd like.
    validations:
      required: true

  - type: textarea
    id: considered_alternative
    attributes:
      label: Considered Alternative
      description: |
        A clear description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: |
        A clear description of any other context or screenshots about your feature request.
    validations:
      required: false
